site_name: python от ods.ai
site_url: https://open-data-science.github.io/pycourse/
copyright: © 2022 - с.г. ods.ai

repo_name: open-data-science/pycourse
repo_url: https://github.com/open-data-science/pycourse
edit_uri: edit/__master__/docs/

theme:
  name: material
  custom_dir: docs/overrides

  static_templates:
    - 404.html

  font:
    text: Golos Text
    code: PT Mono

  favicon: assets/logo.png
  logo: assets/logo.png

  language: ru
  features:
    - announce.dismiss

    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.tabs.link

    # - header.autohide

    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

    - search.highlight
    - search.share
    - search.suggest

  palette:
    scheme: slate
    primary: black
    accent: red

plugins:
  - search:
      lang:
        - en
        - ru
  - minify:
      minify_html: true
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     fallback_to_build_date: true
  #     type: date
  - glightbox


extra:
  generator: false
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/open-data-science/pycourse
    # - icon: fontawesome/brands/matrix
    #   link: ..
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ods_ai

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - главная:
    - index.md
    - authors.md
    - community.md
    - содействие: https://github.com/open-data-science/pycourse/blob/master/contributing.md
    - лицензия: https://github.com/open-data-science/pycourse/blob/master/license
  - основы python:
    - base/index.md
    - установка инструментов: base/tools_install.md
    - ориентация в jupyter: base/jupyter.md
    - переменные, типы и вывод: base/variable_types_output.md
    - условия и сравнения: base/conditional_comparison.md
    - списки и циклы: base/list_loop.md
    - словари: base/dictionary.md
    - функции: base/functions.md
    - объекты, классы и методы: base/object_class_method.md
    - синтаксический сахар: base/syntactic_sugar.md
    - финальная лекция: base/final.md
