name: cd-prod

on:
  workflow_dispatch:
  push:
    branches:
      - __master__

env:
  PUBLISH_BRANCH: pycourse-page-prod

jobs:

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:

      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: caching
        uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: image processing deps
        run: |
          sudo pip install pillow cairosvg
          sudo apt-get install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
          sudo apt-get install pngquant

      - name: deploy mkdocs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: mkdocs build -v

      - name: update publish dir to build branch
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: ${{ env.PUBLISH_BRANCH }}
          publish_dir: ./site
