name: dependency review

on:
  pull_request:
    branches:
      - master
  merge_group:
    types:
      - checks_requested

permissions:
  contents: read

jobs:

  dependency_review:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:

      - name: checkout repository
        uses: actions/checkout@v3

      - name: run dependency review
        uses: actions/dependency-review-action@v3
